services:
   proxy:
      container_name: proxy
      build:
         context: ./proxy
      ports:
         - "8080:8080"
      depends_on:
         - app
         - db

   app:
      container_name: app
      build:
         context: ./node
      depends_on:
         db:
            condition: service_healthy

   db:
      container_name: db
      image: mysql
      healthcheck:
         test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-proot"]
         interval: 5s
         timeout: 5s
         retries: 20
      environment:
         - MYSQL_ROOT_PASSWORD=root
         - MYSQL_DATABASE=desafio_docker_node
      volumes:
         - ./volumes/mysql:/var/lib/mysql
   
     